In [14]:
from urllib.parse import quote_plus

import pandas as pd
from sqlalchemy import create_engine

username = quote_plus("root")
password = quote_plus("1234567890")
server = "127.0.0.1:3307"
db_name = "TESTDB"

conn = create_engine(
    f"mysql+pymysql://{username}:{password}@{server}/{db_name}?autocommit=true",
).connect()

In [15]:
username = quote_plus("ro ot")
password = quote_plus("123456@7890")
server = "127.0.0.1:3307"
db_name = "TESTDB"
print(f"mysql+pymysql://{username}:{password}@{server}/{db_name}")

mysql+pymysql://ro+ot:123456%407890@127.0.0.1:3307/TESTDB

In [16]:
df = pd.read_sql(
    "select * from Staff",
    conn,
)

df

    ID   Name DeptId  Age Gender  Salary            recordDt
0  011   Mike    002   45      M   60000 2020-10-13 21:41:49
1  012   Judy    002   30      F   48000 2020-10-13 21:41:49
2  013  Allen    001   22      M   50000 2020-10-13 21:41:49
3  014    Tom    002   47      M   47000 2020-10-13 21:41:49
4  015   Jack    003   36      M   52000 2020-10-13 21:41:49
5  016   Abby    002   24      F   45000 2020-10-13 21:41:49
6  017  Trump    001   80      M   80000 2020-10-13 21:41:49
7  018  Marry    003   29      F   87000 2020-10-13 21:41:49

In [17]:
df["ID"].str.replace("00", "01")

0    011
1    012
2    013
3    014
4    015
5    016
6    017
7    018
Name: ID, dtype: object

In [18]:
df["ID"].apply(lambda x: x.replace("00", "01"))

0    011
1    012
2    013
3    014
4    015
5    016
6    017
7    018
Name: ID, dtype: object

In [19]:
df["ID"] = df["ID"].str.replace("01", "02")
df

    ID   Name DeptId  Age Gender  Salary            recordDt
0  021   Mike    002   45      M   60000 2020-10-13 21:41:49
1  022   Judy    002   30      F   48000 2020-10-13 21:41:49
2  023  Allen    001   22      M   50000 2020-10-13 21:41:49
3  024    Tom    002   47      M   47000 2020-10-13 21:41:49
4  025   Jack    003   36      M   52000 2020-10-13 21:41:49
5  026   Abby    002   24      F   45000 2020-10-13 21:41:49
6  027  Trump    001   80      M   80000 2020-10-13 21:41:49
7  028  Marry    003   29      F   87000 2020-10-13 21:41:49

In [20]:
df.to_sql(
    "Staff",
    conn,
    if_exists="append",
    index=False,
)

8

In [12]:
conn.commit()

In [21]:
df

    ID   Name DeptId  Age Gender  Salary            recordDt
0  021   Mike    002   45      M   60000 2020-10-13 21:41:49
1  022   Judy    002   30      F   48000 2020-10-13 21:41:49
2  023  Allen    001   22      M   50000 2020-10-13 21:41:49
3  024    Tom    002   47      M   47000 2020-10-13 21:41:49
4  025   Jack    003   36      M   52000 2020-10-13 21:41:49
5  026   Abby    002   24      F   45000 2020-10-13 21:41:49
6  027  Trump    001   80      M   80000 2020-10-13 21:41:49
7  028  Marry    003   29      F   87000 2020-10-13 21:41:49

In [ ]:
df.to_sql(
    "staff",
    conn,
    if_exists="replace",
    index=False,
)

8